List<String> bookCategories = [
  'Action and adventure',
  'Anthology',
  'Art',
  'Autobiography',
  'Biography',
  'Business and economics',
  'Children\'s',
  'Comics',
  'Cookbooks',
  'Diaries and journals',
  'Dictionary',
  'Drama',
  'Encyclopedia',
  'Fantasy',
  'Guide',
  'Health and fitness',
  'Historical fiction',
  'History',
  'Horror',
  'Humor',
  'Memoir',
  'Mystery',
  'Other',
  'Paranormal romance',
  'Picture books',
  'Poetry',
  'Political thriller',
  'Religion, spirituality, and new age',
  'Romance',
  'Satire',
  'Science',
  'Science fiction',
  'Self-help',
  'Short story',
  'Sports',
  'Suspense and thriller',
  'Technology',
  'Travel',
  'True crime',
  'Western'
];

List<String> bookPageRanges = [
  '1-100',
  '101-200',
  '201-300',
  '301-400',
  '401-500',
  '501-600',
  '601-700',
  '701-800',
  '801-900',
  '901-1000',
  '1000+',
];

List<String> bookRentDurations = [
  '1-7 days',
  '8-14 days',
  '15-30 days',
  '1-2 months',
  '2-3 months',
];