List<String> bookCategories = [
  'Action and adventure',
  'Anthology',
  'Art',
  'Autobiography',
  'Biography',
  'Business and economics',
  'Children\'s',
  'Comics',
  'Cookbooks',
  'Diaries and journals',
  'Dictionary',
  'Drama',
  'Encyclopedia',
  'Fantasy',
  'Guide',
  'Health and fitness',
  'Historical fiction',
  'History',
  'Horror',
  'Humor',
  'Memoir',
  'Mystery',
  'Other',
  'Paranormal romance',
  'Picture books',
  'Poetry',
  'Political thriller',
  'Religion, spirituality, and new age',
  'Romance',
  'Satire',
  'Science',
  'Science fiction',
  'Self-help',
  'Short story',
  'Sports',
  'Suspense and thriller',
  'Technology',
  'Travel',
  'True crime',
  'Western'
];

List<String> bookPageRanges = [
  '1-100',
  '101-200',
  '201-300',
  '301-400',
  '401-500',
  '501-600',
  '601-700',
  '701-800',
  '801-900',
  '901-1000',
  '1000+',
];

List<String> bookRentDurations = [
  '1-7 days',
  '8-14 days',
  '15-30 days',
  '1-2 months',
  '2-3 months',
];
List<Map<String, dynamic>> ergs = [
  { "id": "5fc231079bbbd507f6c1c1ce",
    "poster": """https://storage.googleapis.com/connect-plus-4884a.appspot.com/erg-posters/1702473247269_30.jpg""",
    "description": """Is a strong community of a female and male members. WIA’s vision is to have Dell be an employer of choice by creating a supportive environment enabling women to achieve their goals throughout their journey.""",
    "color": """#EE82EE""",
    "name": """Women in Action""",
  },
  { "id": "5fc231299bbbd507f6c1c1d0",
    "poster": """https://storage.googleapis.com/connect-plus-4884a.appspot.com/erg-posters/1702473252888_200.jpg""",
    "description": """is an Employee resource group at Dell Technologies that aims at bridging the gap between cultures and building a culturally intelligent workforce that demonstrates genuine respect for all our multi-cultural customers, partners, vendors and team members. Our vision is to create an inclusive and diverse environment where all community members get to celebrate their differences.""",
    "color": """#FFA500""",
    "name": """Mosaic""",
  },
  { "id": "5fc231649bbbd507f6c1c1d2",
    "poster": """https://storage.googleapis.com/connect-plus-4884a.appspot.com/erg-posters/1702473256177_279.jpg""",
    "description": """Sustainability committee that encourages and helps employees find some time during their busy working week, to pay back to the community through different projects and campaigns which includes 2 ERGs: True Ability and Planet""",
    "color": """#FF0000""",
    "name": """DT BelMasry""",
  },
  { "id": "5fc2319d9bbbd507f6c1c1d4",
    "poster": """https://storage.googleapis.com/connect-plus-4884a.appspot.com/erg-posters/1702473258319_118.jpg""",
    "description": """Internal Communications aims to keep all COE team members connected and informed and have a shared understanding of company goals, values, and guidelines.        

It is critical for keeping all team members up-to-date on a company’s latest initiatives, providing an opportunity for a two-way conversation between members of the COE and its leadership and facilitating streamlined, clear communications among different business units.""",
    "color": """#007db8""",
    "name": """Internal Comms""",
  },
  { "id": "5fc235d49bbbd507f6c1c1d6",
    "poster": """https://storage.googleapis.com/connect-plus-4884a.appspot.com/erg-posters/1702473260451_992.jpg""",
    "description": """Is established to encourage a positive work-life balance at Dell Technologies; creating a unique work environment unlike any other. Our objectives are to strive f
or fun collaborative programs, events and  engage a sense of social and physical wellness through various activities and foster team work through cross collaboration in the company.""",
    "color": """#008000""",
    "name": """GenNext""",
  },
  { "id": "5fd892a0541b7708cebcbc0a",
    "poster": """https://storage.googleapis.com/connect-plus-4884a.appspot.com/erg-posters/1702473265403_866.jpg""",
    "description": """Is focused on informing, educating and making impactful changes throughout the organization; by driving awareness there is better of the competing demands placed on those in a caregiving situation.""",
    "color": """#FF1493""",
    "name": """Family Balance""",
  },
];

List<Map<String, dynamic>> categories = [
  { "id": "5fb80251cc0e0c02a7e53b00",
    "name": """Cars""",
  },
  { "id": "5fb80269cc0e0c02a7e53b01",
    "name": """Lifestyle""",
  },
  { "id": "5fb80297cc0e0c02a7e53b03",
    "name": """Food""",
  },
  { "id": "5fb802b0cc0e0c02a7e53b04",
    "name": """Travel""",
  },
  { "id": "60e1f053e186640f1e87ae10",
    "name": """Technology""",
  },
  { "id": "60ef2e0252ff3b12076b1012",
    "name": """Sports""",
  },
  { "id": "6124fd4752ff3b12076b1060",
    "name": """Bank""",
  },
  { "id": "612f45189c1f9f13c49e715b",
    "name": """Fashion""",
  },
  { "id": "61b2011ceb3ea014a08d0514",
    "name": """Real Estate""",
  },
  { "id": "61eea2ca83a43c000de28b1e",
    "name": """Nurseries""",
  },
  { "id": "61f006ae83a43c000de28b2a",
    "name": """Medical""",
  },
];

